"use client";

import { useEffect, useState } from "react";
import { Button } from "@heroui/react";
import { Mail, Save, Send } from "lucide-react";
import { PageHeader } from "@/components/page-header";

type SMTPSettings = { host: string; port: number; username: string; password: string; auth: boolean; encryptType: "STARTTLS" | "SSL" | "NONE"; encryptPort: number; fromEmail: string; fromName: string };
const emptySettings: SMTPSettings = { host: "", port: 465, username: "", password: "", auth: true, encryptType: "SSL", encryptPort: 465, fromEmail: "", fromName: "CertFlow" };

export default function SettingsPage() {
  const [settings, setSettings] = useState<SMTPSettings>(emptySettings); const [loaded, setLoaded] = useState(false); const [pending, setPending] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/settings/smtp").then(async (response) => { if (!response.ok) throw new Error("无权访问设置"); return response.json(); }).then((body) => { if (body.settings) setSettings({ ...emptySettings, ...body.settings }); setLoaded(true); }).catch((reason) => { setError(reason instanceof Error ? reason.message : "无法加载设置"); setLoaded(true); }); }, []);
  function update<K extends keyof SMTPSettings>(key: K, value: SMTPSettings[K]) { setSettings((current) => ({ ...current, [key]: value })); }
  function updateEncryption(encryptType: SMTPSettings["encryptType"]) {
    setSettings((current) => {
      const shouldUseStartTLSPort = encryptType === "STARTTLS" && current.encryptPort === 465;
      const shouldUseSSLPort = encryptType === "SSL" && current.encryptPort === 587;
      const encryptPort = shouldUseStartTLSPort ? 587 : shouldUseSSLPort ? 465 : current.encryptPort;
      return { ...current, encryptType, encryptPort, port: current.port === current.encryptPort ? encryptPort : current.port };
    });
  }
  async function save(event: React.FormEvent) { event.preventDefault(); setPending(true); setError(""); setMessage(""); try { const response = await fetch("/api/settings/smtp", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(settings) }); const body = await response.json().catch(() => null) as { message?: string } | null; if (!response.ok) throw new Error(body?.message ?? "保存失败"); setSettings((current) => ({ ...current, password: "" })); setMessage("SMTP 设置已保存。"); } catch (reason) { setError(reason instanceof Error ? reason.message : "保存失败"); } finally { setPending(false); } }
  async function test() { setPending(true); setError(""); setMessage(""); try { const response = await fetch("/api/settings/smtp/test", { method: "POST" }); const body = await response.json().catch(() => null) as { message?: string } | null; if (!response.ok) throw new Error(body?.message ?? "测试邮件发送失败"); setMessage("测试邮件已发送到当前管理员邮箱。"); } catch (reason) { setError(reason instanceof Error ? reason.message : "测试失败"); } finally { setPending(false); } }
  if (!loaded) return <><PageHeader title="设置" description="系统服务配置" /><div className="empty-state">正在加载设置...</div></>;
  return <><PageHeader title="设置" description="管理员可配置系统邮件服务。SMTP 密码会加密保存，读取时不会回显。" /><form className="form-section settings-form" onSubmit={save}><h2><Mail size={17} /> SMTP 发件邮箱</h2><div className="field-grid"><label className="field"><span>SMTP 主机</span><input value={settings.host} onChange={(event) => update("host", event.target.value)} required placeholder="smtp.feishu.cn" /></label><label className="field"><span>连接端口</span><input value={settings.port} onChange={(event) => update("port", Number(event.target.value))} type="number" min="1" max="65535" required /></label><label className="field"><span>用户名</span><input value={settings.username} onChange={(event) => update("username", event.target.value)} autoComplete="username" required /></label><label className="field"><span>密码</span><input value={settings.password} onChange={(event) => update("password", event.target.value)} type="password" autoComplete="new-password" placeholder="留空表示不修改已保存密码" /></label><label className="field"><span>发件邮箱（可选）</span><input value={settings.fromEmail} onChange={(event) => update("fromEmail", event.target.value)} type="email" placeholder="默认使用用户名" /></label><label className="field"><span>发件人名称</span><input value={settings.fromName} onChange={(event) => update("fromName", event.target.value)} /></label><label className="field"><span>加密类型</span><select value={settings.encryptType} onChange={(event) => updateEncryption(event.target.value as SMTPSettings["encryptType"])}><option value="SSL">SSL（隐式 TLS）</option><option value="STARTTLS">STARTTLS</option><option value="NONE">无加密</option></select></label><label className="field"><span>加密端口</span><input value={settings.encryptPort} onChange={(event) => update("encryptPort", Number(event.target.value))} type="number" min="1" max="65535" required /></label><label className="field field-wide"><span className="checkbox-field"><input checked={settings.auth} onChange={(event) => update("auth", event.target.checked)} type="checkbox" /> 启用 SMTP AUTH</span></label></div>{message ? <div className="auth-message">{message}</div> : null}{error ? <div className="form-error">{error}</div> : null}<div className="form-actions"><Button type="button" variant="secondary" onPress={test} isDisabled={pending}><Send size={16} /> 测试发信</Button><Button type="submit" variant="primary" isDisabled={pending}><Save size={16} /> {pending ? "正在保存" : "保存设置"}</Button></div></form></>;
}
